### ISSUE TITLE
Meteor organization name

### ISSUE THREAD

**Issue by zimme** [klaussner/meteor-svelte#1]
Hey, I'm sitting on svelte and sveltejs meteor organization names, give me your meteor login name if you want me to add you to the orgs if you want to publish the package under svelte:compiler or sveltejs:compiler or something like that.

**Comment by zimme** [comment]
I was going to do what you've done here but I got side tracked so I'm glad you beat me to it =)

**Comment by zimme** [comment]
I've created meteor-svelte github organization and invited you in the case you wanna host the code under it's own github org for this project. I've decided to go this route with my most popular packages so that the community have it easier to take over maintenance if I ever don't have time.

But it's completely up to you, but now you have the option =)

**Comment by klaussner** [comment]
Thanks @zimme, that's a great idea! :blush: I'm going to add the Tracker and Apollo integration packages that I'm currently working on to the organization soon. How would you handle moving the `meteor-svelte` project? I thought about publishing a new version of the current Atmosphere package that shows a deprecation warning and the new `svelte:compiler` name when it's loaded.

**Comment by klaussner** [comment]
My Meteor login is `klaussner`.

**Comment by zimme** [comment]
I've added you to the meteor organisation svelte and sveltejs now.

I'd just move this repo to the organisation that way history and stuff is retained,
update all the links to the old repo in package.json and other places.

As for the package itself, I'd publish a new version of the package which implies the new package and prints a warning to the console that the package has been deprecated in favor of the new one.

**Comment by klaussner** [comment]
Could you give me admin rights for the organization? I'd like to add an image.

**Comment by zimme** [comment]
There, should be done.

**Comment by klaussner** [comment]
Thanks! :slightly_smiling_face:
